get http://localhost:3001/api/users

###
post http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "pptest",
  "password": "pass",
  "name": "test"
}
###
patch http://localhost:3001/api/users/random-user/profile
Content-Type: application/json

{
  "photoNumber": 2
}

###
delete http://localhost:3001/api/users/601b9ae8811f6e23c5bc865d

###
post http://localhost:3001/api/flashcards
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmZTkwMjJjMzBiYjE5YWYwYWVmMDhkZSIsImlhdCI6MTYwOTEwNjA3MH0.DGb9SDQKbIshnUSXMq68aTQ51vdKiYYeny41oM7VSwY

{
  "front": "test testdb front",
  "back":"testdb back",
}

###
delete http://localhost:3001/api/flashcards/5fcdb9f2c5eaea368e0e21da
